version: "3.8"

services:
  postgres:
    image: postgres:17.4
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      retries: 20
    networks:
      - app_network

  web:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      selenium:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app_network

  selenium:
    image: selenium/standalone-firefox:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5313:4444"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:4444/status || exit 1"]
      interval: 1s
      retries: 20
      start_period: 10s

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
